2020/05/12 11:41:11 [error] 6#6: *1 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2020/05/12 11:41:11 [error] 6#6: *1 open() "/etc/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.26.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2020/05/12 11:41:12 [error] 6#6: *1 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2020/05/12 11:41:13 [error] 6#6: *1 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.26.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2020/05/12 15:55:52 [error] 6#6: *1 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.28.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2020/05/12 15:55:53 [error] 6#6: *1 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.28.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2020/05/12 15:55:53 [error] 6#6: *1 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.28.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2020/05/12 15:55:54 [error] 6#6: *1 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.28.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2020/05/12 15:58:17 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:80/", host: "jenkins.backendteam.xyz"
2020/05/12 15:58:17 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET /robots.txt HTTP/1.1", upstream: "http://172.28.0.2:80/robots.txt", host: "jenkins.backendteam.xyz"
2020/05/12 15:58:17 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:80/favicon.ico", host: "jenkins.backendteam.xyz", referrer: "http://jenkins.backendteam.xyz/"
2020/05/12 15:58:18 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:80/", host: "jenkins.backendteam.xyz"
2020/05/12 15:58:18 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:80/favicon.ico", host: "jenkins.backendteam.xyz", referrer: "http://jenkins.backendteam.xyz/"
2020/05/12 15:58:18 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:80/", host: "jenkins.backendteam.xyz"
2020/05/12 15:58:19 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:80/favicon.ico", host: "jenkins.backendteam.xyz", referrer: "http://jenkins.backendteam.xyz/"
2020/05/12 15:58:19 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:80/", host: "jenkins.backendteam.xyz"
2020/05/12 15:58:19 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:80/favicon.ico", host: "jenkins.backendteam.xyz", referrer: "http://jenkins.backendteam.xyz/"
2020/05/12 15:58:19 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:80/", host: "jenkins.backendteam.xyz"
2020/05/12 15:58:19 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:80/favicon.ico", host: "jenkins.backendteam.xyz", referrer: "http://jenkins.backendteam.xyz/"
2020/05/12 15:58:19 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:80/", host: "jenkins.backendteam.xyz"
2020/05/12 15:58:19 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:80/favicon.ico", host: "jenkins.backendteam.xyz", referrer: "http://jenkins.backendteam.xyz/"
2020/05/12 15:58:23 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET /jenkins HTTP/1.1", upstream: "http://172.28.0.2:80/jenkins", host: "jenkins.backendteam.xyz"
2020/05/12 15:58:23 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:80/favicon.ico", host: "jenkins.backendteam.xyz", referrer: "http://jenkins.backendteam.xyz/jenkins"
2020/05/12 15:58:24 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET /jenkins HTTP/1.1", upstream: "http://172.28.0.2:80/jenkins", host: "jenkins.backendteam.xyz"
2020/05/12 15:58:24 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:80/favicon.ico", host: "jenkins.backendteam.xyz", referrer: "http://jenkins.backendteam.xyz/jenkins"
2020/05/12 15:58:25 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET /jenkins HTTP/1.1", upstream: "http://172.28.0.2:80/jenkins", host: "jenkins.backendteam.xyz"
2020/05/12 15:58:25 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:80/favicon.ico", host: "jenkins.backendteam.xyz", referrer: "http://jenkins.backendteam.xyz/jenkins"
2020/05/12 15:58:26 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:80/", host: "jenkins.backendteam.xyz"
2020/05/12 15:58:26 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:80/favicon.ico", host: "jenkins.backendteam.xyz", referrer: "http://jenkins.backendteam.xyz/"
2020/05/12 16:03:59 [error] 7#7: *2 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET / HTTP/1.1", host: "jenkins.backendteam.xyz"
2020/05/12 16:06:05 [error] 7#7: *51 open() "/etc/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.28.0.1, server: jenkins.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", host: "jenkins.backendteam.xyz", referrer: "http://jenkins.backendteam.xyz/jenkins/login?from=%2Fjenkins%2F"
2020/05/12 16:23:42 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8080/", host: "nexus.backendteam.xyz"
2020/05/12 16:23:42 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /robots.txt HTTP/1.1", upstream: "http://172.28.0.2:8080/robots.txt", host: "nexus.backendteam.xyz"
2020/05/12 16:23:43 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8080/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:23:44 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8080/", host: "nexus.backendteam.xyz"
2020/05/12 16:23:44 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8080/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:23:45 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8080/", host: "nexus.backendteam.xyz"
2020/05/12 16:23:45 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8080/", host: "nexus.backendteam.xyz"
2020/05/12 16:23:45 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8080/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:23:45 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8080/", host: "nexus.backendteam.xyz"
2020/05/12 16:23:45 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8080/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:24:46 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:46 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8081/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:24:47 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:47 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8081/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:24:47 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:47 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8081/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:24:47 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:48 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8081/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:24:48 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:48 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8081/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:24:48 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:48 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8081/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:24:48 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:48 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8081/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:24:48 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:48 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8081/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:24:48 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:49 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8081/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:24:49 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:49 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8081/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:24:49 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:49 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:49 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8081/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:24:49 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:50 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8081/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:24:50 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:50 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8081/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:24:50 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:50 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8081/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:24:50 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.2:8081/", host: "nexus.backendteam.xyz"
2020/05/12 16:24:51 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: nexus.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.2:8081/favicon.ico", host: "nexus.backendteam.xyz", referrer: "http://nexus.backendteam.xyz/"
2020/05/12 16:35:36 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:37:23 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:10080/", host: "gitlab.backendteam.xyz"
2020/05/12 16:37:23 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /robots.txt HTTP/1.1", upstream: "http://172.28.0.5:10080/robots.txt", host: "gitlab.backendteam.xyz"
2020/05/12 16:37:24 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:10080/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:37:24 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:10080/", host: "gitlab.backendteam.xyz"
2020/05/12 16:37:25 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:10080/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:37:25 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:10080/", host: "gitlab.backendteam.xyz"
2020/05/12 16:37:25 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:10080/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:37:25 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:10080/", host: "gitlab.backendteam.xyz"
2020/05/12 16:37:25 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:10080/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:37:26 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:10080/", host: "gitlab.backendteam.xyz"
2020/05/12 16:37:26 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:10080/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:37:26 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:10080/", host: "gitlab.backendteam.xyz"
2020/05/12 16:37:26 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:10080/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:37:26 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:10080/", host: "gitlab.backendteam.xyz"
2020/05/12 16:37:26 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:10080/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:37:26 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:10080/", host: "gitlab.backendteam.xyz"
2020/05/12 16:37:27 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:10080/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:38:52 [error] 6#6: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:10080/", host: "gitlab.backendteam.xyz"
2020/05/12 16:38:53 [error] 6#6: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:10080/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:38:53 [error] 6#6: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:10080/", host: "gitlab.backendteam.xyz"
2020/05/12 16:38:54 [error] 6#6: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:10080/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:38:54 [error] 6#6: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:10080/", host: "gitlab.backendteam.xyz"
2020/05/12 16:38:54 [error] 6#6: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:10080/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:38:54 [error] 6#6: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:10080/", host: "gitlab.backendteam.xyz"
2020/05/12 16:38:54 [error] 6#6: *21 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:10080/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:39:46 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:39:47 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:39:47 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:39:48 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:39:49 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:39:51 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:39:55 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:40:31 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:40:50 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:40:50 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:40:51 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:40:51 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:40:51 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:40:51 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:40:52 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:40:52 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:40:52 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:40:52 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:40:52 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:40:52 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:40:52 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:40:52 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:40:53 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:41:35 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:41:35 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:41:37 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:41:37 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:41:37 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:41:38 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:41:38 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:41:38 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:41:38 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:41:38 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:41:38 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:41:38 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:41:38 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:41:38 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:41:39 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:41:39 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:41:39 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:41:39 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:41:39 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:41:39 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:42:32 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:43:40 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:43:40 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:43:41 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:43:42 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:43:43 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:43:45 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:43:48 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:43:55 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/12 16:44:09 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET / HTTP/1.1", upstream: "http://172.28.0.4:8084/", host: "gitlab.backendteam.xyz"
2020/05/12 16:44:10 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: gitlab.backendteam.xyz, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.4:8084/favicon.ico", host: "gitlab.backendteam.xyz", referrer: "http://gitlab.backendteam.xyz/"
2020/05/12 16:52:14 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
2020/05/13 00:55:09 [emerg] 1#1: host not found in upstream "gitlab" in /etc/nginx/conf.d/default.conf:11
